name: Build and Archive APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate access token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_KEY }}
          repositories: "Zephyra77/CloudStreming"

      - name: Generate archive token
        id: generate_archive_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_KEY }}
          repositories: "Zephyra77/cloudstream-archive"

      - uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Fetch keystore
        id: fetch_keystore
        run: |
          TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}/keystore"
          mkdir -p "${TMP_KEYSTORE_FILE_PATH}"
          curl -H "Authorization: token ${{ steps.generate_token.outputs.token }}" \
               -o "${TMP_KEYSTORE_FILE_PATH}/prerelease_keystore.keystore" \
               "https://raw.githubusercontent.com/Zephyra77/secrets/main/keystore.jks"
          curl -H "Authorization: token ${{ steps.generate_token.outputs.token }}" \
               -o "keystore_password.txt" \
               "https://raw.githubusercontent.com/Zephyra77/secrets/main/keystore_password.txt"
          KEY_PWD="$(cat keystore_password.txt)"
          echo "::add-mask::${KEY_PWD}"
          echo "key_pwd=$KEY_PWD" >> $GITHUB_OUTPUT

      - name: Build APK
        run: ./gradlew assemblePrerelease
        env:
          SIGNING_KEY_ALIAS: "key0"
          SIGNING_KEY_PASSWORD: ${{ steps.fetch_keystore.outputs.key_pwd }}
          SIGNING_STORE_PASSWORD: ${{ steps.fetch_keystore.outputs.key_pwd }}
          SIMKL_CLIENT_ID: ${{ secrets.SIMKL_CLIENT_ID }}
          SIMKL_CLIENT_SECRET: ${{ secrets.SIMKL_CLIENT_SECRET }}

      - uses: actions/checkout@v5
        with:
          repository: "Zephyra77/cloudstream-archive"
          token: ${{ steps.generate_archive_token.outputs.token }}
          path: archive

      - name: Move APK to archive
        run: |
          cp app/build/outputs/apk/prerelease/release/*.apk "archive/$(git rev-parse --short HEAD).apk"

      - name: Push archive
        run: |
          cd archive
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Build $GITHUB_SHA" || exit 0
          git push --force
